//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void setup(); \
	void loop(); \
	void updateDialLabel(); \
	void createDialScale(); \
	void drawEmptyDial(String label, int16_t val); \
	void plotDial(int16_t x, int16_t y, int16_t angle, String label, uint16_t val); \
	void createNeedle(void); \

